@TodoApi_HostAddress = https://localhost:7226

GET {{TodoApi_HostAddress}}/todoitems/

###

POST {{TodoApi_HostAddress}}/todoitems/

###

POST {{TodoApi_HostAddress}}/todoitems/

###

POST {{TodoApi_HostAddress}}/todoitems/

###

POST {{TodoApi_HostAddress}}/todoitems/

###

GET {{TodoApi_HostAddress}}/todoitems/

###
